spring.application.name=rising-pulse-app
server.port=8040

spring.datasource.url=jdbc:postgresql://localhost:5432/rising-pulse
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false
springdoc.swagger-ui.doc-expansion=none

